# -*- coding: utf-8 -*-
"""updated_fitting_functions_multiple_times.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14bkOvX4ATOqnjlSnsR4tr78cFJUlBsj-
"""

import numpy as np

def fit_multiple_times(iternum, model, dataset):
  collection_of_parameters = np.zeros(0)
  collection_of_loglikelihood = np.zeros(0)
  
  try:
    param_est = model.optimizing(data=dataset)
    collection_of_parameters = np.append(collection_of_parameters,param_est)
    collection_of_loglikelihood = np.append(collection_of_loglikelihood, param_est['loglikelihood'])
  except:
    print('there is something wrong with stan model fitting')
    param_est = model.optimizing(data=dataset, iter=iternum)
    collection_of_parameters = np.append(collection_of_parameters,param_est)
    collection_of_loglikelihood = np.append(collection_of_loglikelihood, param_est['loglikelihood'])

  find_max = max(collection_of_loglikelihood)

  for i in range(len(collection_of_parameters)):
    if collection_of_parameters[i]['loglikelihood'] == find_max:
      return collection_of_parameters[i]
  
  return collection_of_parameters[i]